import Head from 'next/head'
import Footer from './Footer/Footer'
import Category from './category/Category'
import Welcome from './Header/Welcome'
import Map from './Footer/Map'

export default function Home() {
  return (
    <>
      <Head>
        <title>PHN Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Welcome />
        <Category />
        <Map />
        <Footer />
      </main>
    </>
  )
}
